profiles:
    default:
        model: geminiflash
        prompt: full-analysis
    sonnet:
        model: sonnet35
        prompt: full-analysis
    qwen:
        model: qwen32b
        prompt: full-analysis
    qwen-r1:
        model: deepseekr1
        prompt: full-analysis
    qwen-max:
        model: qwenmax
        prompt: full-analysis
    security:
        model: geminiflash
        prompt: vulnerability-scan

    refactor-sonnet:
        model: sonnet35
        prompt: single-refactor
    refactor-r1-free:
        model: deepseekr1free
        prompt: single-refactor
    refactor-ds3-free:
        model: deepseekchatfree
        prompt: single-refactor
    refactor-qwen-r1:
        model: deepseekr1
        prompt: single-refactor
    refactor-qwen-r1-free:
        model: deepseekr1:free
        prompt: single-refactor
    refactor-qwq-free:
        model: qwq32b:free
        prompt: single-refactor
    refactor-qwen:
        model: qwen32b
        prompt: single-refactor
    refactor-qwq:
        model: qwq32b
        prompt: single-refactor


    good-bad-ugly-gemini:
        model: gemini25pro-free
        prompt: good-bad-ugly
        
    good-bad-ugly-sonnet:
        model: sonnet37
        prompt: good-bad-ugly

