profiles:
    default:
        model: geminiflash20-free
        strategy: wholefile
    m2:
        model: m2
        strategy: wholefile
    flash20-free:
        model: geminiflash20-free
        strategy: wholefile
    flash25:
        model: geminiflash25
        strategy: wholefile
    flash25-lite:
        model: geminiflash25-lite
        strategy: wholefile
    qwen:
        model: qwen32b
        strategy: searchreplace
#    sonnet37:
#        model: sonnet37
#        strategy: searchreplace
    sonnet45:
        model: sonnet45
        strategy: searchreplace

# TODO: new section defaultProfiles: ... a list of commenter profiles to use by default [start with 1st, if it fails, try 2nd, etc]