profiles:
    default:
        model: geminiflash20-free
        strategy: wholefile
    m2:
        model: m2-free
        strategy: wholefile
    geminiflash20:
        model: geminiflash20-free
        strategy: wholefile
    geminiflash25:
        model: geminiflash25
        strategy: wholefile
    qwen:
        model: qwen32b
        strategy: searchreplace
    sonnet:
        model: claude37
        strategy: searchreplace

# TODO: new section defaultProfiles: ... a list of commenter profiles to use by default [start with 1st, if it fails, try 2nd, etc]